#Fun fact: I've never felt an earthquake in my life
#Thu May 28 08:53:20 CLT 2026
alertGlobal=true
alertGlobalMag=6.0
alertLocal=true
alertLocalDist=200.0
alertPossibleShaking=true
alertPossibleShakingDistance=30000.0
alertRegion=true
alertRegionDist=1000.0
alertRegionMag=3.5
antialiasing=false
cinemaModeOnStartup=true
cinemaModeReenable=true
cinemaModeSwitchTime=10
cinemaModeZoomMultiplier=100
confidencePolygons=false
displayAdditionalQuakeInfo=false
displayAlertBox=true
displayArchivedQuakes=true
displayCapitalCities=true
displayCityIntensities=true
displayClusterRoots=false
displayClusters=false
displayCoreWaves=false
displayHomeLocation=true
displayMagnitudeHistogram=true
displayShakemaps=true
displaySystemInfo=true
displayTime=true
distanceUnitsIndex=0
earthquakeSoundsMaxDist=30000.0
earthquakeSoundsMinMagnitude=0.0
eewClusterLevel=2
eewLevelIndex=5
eewScale=0
enableEarthquakeSounds=true
enableSound=true
focusOnEvent=true
fpsIdle=30
globalVolume=100
hideDeadStations=false
homeLat=0.0
homeLon=0.0
hypocenterCorrectThreshold=50.0
hypocenterDetectionResolution=64.0
intensityScaleIndex=0
jumpToAlert=true
lastServerIP=0.0.0.0
lastServerPORT=38000
logsStoreTimeMinutes=5
maxArchivedQuakes=100
maxClients=64
maxEvents=60
minimumStationsForEEW=5
oldEventsMagnitudeFilter=4.0
oldEventsMagnitudeFilterEnabled=false
oldEventsOpacity=100.0
oldEventsTimeFilter=24.0
oldEventsTimeFilterEnabled=false
pWaveInaccuracyThreshold=1800.0
parallelHypocenterLocations=true
qualityFilter=4
recalibrateOnLaunch=true
reduceRevisions=true
reportsEnabled=false
selectedDateFormatIndex=0
selectedEventColorIndex=0
shakingLevelIndex=0
shakingLevelScale=0
stationIntensityVisibilityZoomLevel=0.2
stationsShapeIndex=0
stationsSizeMul=1.0
strongShakingLevelIndex=5
strongShakingLevelScale=0
timezoneStr=America/Santiago
use24HFormat=true
useOldColorScheme=false
